[project]
name = "dsp-tp3-livraria"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beanie>=1.29.0",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.115.8",
    "motor>=3.7.0",
]
